import click
import numpy as np
import pandas as pd
import os
from pathlib import Path

from pvs.geometry import build_prime_vector
from pvs.weights import gpy_weight # Assuming this will be used in analyse

# Helper function to ensure data directory exists
def ensure_data_dir(ctx, param, value):
    if value:
        path = Path(value)
        path.mkdir(parents=True, exist_ok=True)
        return path
    # If no path provided, use default ./data/processed
    default_path = Path.cwd() / "data" / "processed"
    default_path.mkdir(parents=True, exist_ok=True)
    return default_path

@click.group()
def cli():
    """
    Prime Vector Space (PVS) command-line tool.
    Used for generating prime vectors and performing analysis.
    """
    pass

@cli.command()
@click.option('--max-n', type=int, required=True, help="Maximum number (n) to generate prime vectors up to.")
@click.option('--output-dir', type=click.Path(),
              callback=ensure_data_dir, default=None, # Uses cwd/data/processed by default
              help="Directory to save the output Parquet file. Defaults to ./data/processed/")
@click.option('--filename', type=str, default=None, help="Custom filename for the Parquet file. Defaults to prime_vector_<max_n>.parquet.")
def generate(max_n: int, output_dir: Path, filename: str):
    """
    Generates prime vectors up to --max-n and saves them to a Parquet file.
    The Parquet file will contain a single column 'primes' with the prime vector.
    """
    if max_n < 0:
        click.echo(f"Error: --max-n must be a non-negative integer. Got {max_n}", err=True)
        return

    click.echo(f"Generating prime vector up to n = {max_n}...")

    prime_vector_sparse = build_prime_vector(max_n)

    # Convert sparse matrix to a Pandas Series for easy Parquet writing
    # We store the dense representation, or decide on a sparse format if preferred for Parquet.
    # For now, let's assume we want to store the positions of primes.
    # If max_n is very large, storing dense vector is not feasible.
    # The build_prime_vector returns a sparse CSR matrix.
    # We can store this sparse matrix efficiently.
    # Option 1: Store as a list of prime indices
    prime_indices = prime_vector_sparse.indices
    df = pd.DataFrame({'prime_indices': prime_indices})

    # Option 2: Store in a way that scipy.sparse can reconstruct, e.g., data, indices, indptr
    # For a single vector, 'indices' (column indices of non-zero elements) is sufficient.
    # 'data' is all ones, 'indptr' would be [0, nnz].

    if filename is None:
        output_filename = f"prime_vector_{max_n}.parquet"
    else:
        # Ensure filename has .parquet extension
        if not filename.endswith(".parquet"):
            filename += ".parquet"
        output_filename = filename

    output_path = output_dir / output_filename

    try:
        df.to_parquet(output_path)
        click.echo(f"Successfully saved prime vector to {output_path}")
    except Exception as e:
        click.echo(f"Error saving Parquet file: {e}", err=True)


@cli.command()
@click.option('--input-file', type=click.Path(exists=True, dir_okay=False, readable=True), required=True,
              help="Path to the Parquet file containing prime vectors (from 'generate' command).")
@click.option('--k', type=int, default=2, show_default=True, help="Parameter k for GPY weights (number of primes in a tuple).")
@click.option('--u-factor', type=float, default=0.5, show_default=True,
              help="Factor to determine 'u' for GPY weights, e.g., u = u-factor * log(max_n_from_file).")
@click.option('--plot/--no-plot', default=False, help="Enable/disable plotting of results (requires matplotlib).")
def analyse(input_file: str, k: int, u_factor: float, plot: bool):
    """
    Performs analysis on prime vectors.
    Currently, it computes conceptual GPY weights and θ angle statistics (placeholder).
    """
    click.echo(f"Analysing prime vectors from: {input_file}")
    click.echo(f"Parameters: k={k}, u-factor={u_factor}, Plotting: {'Enabled' if plot else 'Disabled'}")

    try:
        df = pd.read_parquet(input_file)
    except Exception as e:
        click.echo(f"Error reading Parquet file {input_file}: {e}", err=True)
        return

    if 'prime_indices' not in df.columns:
        click.echo(f"Error: 'prime_indices' column not found in {input_file}.", err=True)
        click.echo("Please ensure the Parquet file was generated by the 'generate' command.", err=True)
        return

    prime_indices = df['prime_indices'].values
    if len(prime_indices) == 0:
        max_n_from_file = 0 # Or handle as error, or infer from filename if needed
        click.echo("Warning: No primes found in the input file.")
    else:
        max_n_from_file = prime_indices[-1] if len(prime_indices) > 0 else 0


    # Compute GPY weights (conceptual)
    # u is often related to log(N) where N is the max prime considered.
    if max_n_from_file <= 1: # log(1) is 0, log(0) is undefined.
        # Heuristic: if max_n is very small, u needs a sensible default or handling.
        # For simplicity, if max_n is too small for log to be meaningful, use a small default for u.
        u_param = 1.0 if max_n_from_file <=1 else u_factor * np.log(max_n_from_file)
        if u_param <=0: u_param = 1.0 # Ensure u is positive for gpy_weight
    else:
        u_param = u_factor * np.log(max_n_from_file)

    try:
        weights = gpy_weight(k, u_param)
        click.echo(f"Computed GPY weights (k={k}, u={u_param:.2f}): {weights}")
    except ValueError as e:
        click.echo(f"Error computing GPY weights: {e}", err=True)
        return

    # Placeholder for θ angle statistics computation
    # This would involve using the prime_indices and weights to calculate
    # some statistics related to the distribution of primes, possibly via Maynard's methods.
    # For example, M_k = sum_{n} (sum_{i=1 to k} chi(n+h_i) - log(3N))^2 * lambda_n^2
    # where chi is indicator for primes, lambda_n are GPY weights.
    # Theta would be derived from these sums.

    # Conceptual: Sum of weights (not a real statistic, just to use the numbers)
    theta_statistic_placeholder = np.sum(weights) * np.mean(prime_indices) if len(prime_indices) > 0 else 0
    click.echo(f"Placeholder θ angle statistic: {theta_statistic_placeholder:.4f}")

    if plot:
        try:
            import matplotlib.pyplot as plt
            click.echo("Plotting is enabled. Displaying a conceptual plot...")

            fig, ax = plt.subplots(1, 2, figsize=(12, 5))

            # Plot 1: Distribution of prime_indices (if any)
            if len(prime_indices) > 0:
                ax[0].hist(prime_indices, bins=min(50, len(prime_indices)), color='skyblue', edgecolor='black')
                ax[0].set_title(f"Distribution of Prime Indices (up to {max_n_from_file})")
                ax[0].set_xlabel("Prime Number")
                ax[0].set_ylabel("Frequency (in bins)")
            else:
                ax[0].text(0.5, 0.5, "No prime data to plot.", horizontalalignment='center', verticalalignment='center', transform=ax[0].transAxes)
                ax[0].set_title("Prime Distribution")


            # Plot 2: GPY Weights
            ax[1].bar(range(len(weights)), weights, color='lightgreen', edgecolor='black')
            ax[1].set_title(f"Conceptual GPY Weights (k={k}, u={u_param:.2f})")
            ax[1].set_xlabel("Weight Index")
            ax[1].set_ylabel("Weight Value")
            ax[1].set_xticks(range(len(weights)))

            plt.tight_layout()
            # In a script, you might save this or show it.
            # For a CLI tool, often saving is preferred.
            plot_filename = Path(input_file).stem + "_analysis_plot.png"
            plt.savefig(plot_filename)
            click.echo(f"Plot saved to {plot_filename}")
            # plt.show() # This would block in a script; avoid for automated CLI tool.

        except ImportError:
            click.echo("Matplotlib is not installed. Please install it with 'poetry install --extras viz' to use plotting.", err=True)
        except Exception as e:
            click.echo(f"An error occurred during plotting: {e}", err=True)

if __name__ == '__main__':
    cli()
